#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AmmoMagazines

#include "Basic.hpp"

#include "EAmmoType_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct AmmoMagazines.AmmoMagazines
// 0x000C (0x000C - 0x0000)
struct FAmmoMagazines final
{
public:
	EAmmoType                                     AmmoType_5_1CD642D04C3BF1F857D9EBBF2F2EF4F5;       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Quantity_4_50296D3443367E8FA683FAA68E169687;       // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxQuantity_8_546EA24A4AE28730EF32C0869D82333D;    // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FAmmoMagazines;

SDK_NAMESPACE_END
