#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Base_GM

#include "Basic.hpp"

#include "E_AI_Difficulty_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "EPlayerClass_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Base_GM.BP_Base_GM_C
// 0x00D0 (0x03D8 - 0x0308)
class ABP_Base_GM_C : public AGameMode
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         TimeDilationTimeline_TimeDilation_4E0F90B64A3A72D68D02ACB8159EBC91; // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TimeDilationTimeline__Direction_4E0F90B64A3A72D68D02ACB8159EBC91; // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31D[0x3];                                      // 0x031D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TimeDilationTimeline;                              // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class APlayerController*>              AllPlayersPCs;                                     // 0x0328(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_PlayerSpawn_C*>              PossibleSpawnsA;                                   // 0x0338(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_PlayerSpawn_C*>              PossibleSpawnsB;                                   // 0x0348(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          bGameOver;                                         // 0x0358(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bAllowBots;                                        // 0x0359(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bFriendlyFire;                                     // 0x035A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35B[0x1];                                      // 0x035B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FriendlyDmgMultiplier;                             // 0x035C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TeamABots;                                         // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TeamBBots;                                         // 0x0364(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_PlayerSpawn_C*>              PlayerSpawnsA;                                     // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_PlayerSpawn_C*>              PlayerSpawnsB;                                     // 0x0378(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	float                                         MinSpawnEnemyDistance;                             // 0x0388(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38C[0x4];                                      // 0x038C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AController*>                    TeamABotsControllers;                              // 0x0390(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class AController*>                    TeamBBotsControllers;                              // 0x03A0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         TeamAScore;                                        // 0x03B0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TeamBScore;                                        // 0x03B4(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TimeToReset;                                       // 0x03B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BC[0x4];                                      // 0x03BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerSpawn_C*                      SelectedSpawn;                                     // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBehaviorTree*                          AI_BehaviorTree;                                   // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bUseAutoTeamBalance;                               // 0x03D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	E_AI_Difficulty                               AI_Difficulty;                                     // 0x03D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bPlayerCanChangeTeam;                              // 0x03D2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          FFAMode;                                           // 0x03D3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void DestroyGameModeActors();
	void ChooseSpawnDM(TArray<class ABP_PlayerSpawn_C*>& Spawns, int32 Team, TArray<class ABP_PlayerSpawn_C*>* BestSpawns);
	void AutoTeamBalanceUponDeath(class AController* PlayerController);
	void CheckTeamBalance(class AController* PlayerController, bool* NoSwap);
	class UClass* GetDefaultPawnClassForController(class AController* InController_GetDefaultPawnClassForController);
	void SetGameWithBots(bool bAllowBots);
	void SetGameOver(bool bGameOver);
	void SetFriedlyFire(bool bFriendlyFire);
	void ShowCharacterSelection_Screen(class APlayerController* NewPlayer);
	void SetAIDifficulty();
	void AutoBalanceTeam();
	void AutoTeamBalance_InitialTeam(class AController* PlayerController);
	void HandleFriendlyFireDamage(float Damage, float* DamageToDo);
	void OverrideNumberOfBots(int32 TeamA, int32 TeamB);
	void OnRep_AllPlayersPCs();
	void DestroyBotsPlayerState();
	void UnpossesBots();
	bool ReadyToStartMatch();
	bool ReadyToEndMatch();
	void PossesPawn(class AActor* Pawn, class APlayerController* Controller, const struct FTransform& Transform);
	void SendKillFeedInfo(class APlayerState* Kill, class APlayerState* Vic, const class UDamageType* DmgType, class APlayerState* Assist, bool bHeadshot);
	void ChooseSpawn(TArray<class ABP_PlayerSpawn_C*>& Spawns, int32 Team, TArray<class ABP_PlayerSpawn_C*>* BestSpawns);
	void GetPlayerSpawns(bool FFA);
	void AllPosibleSpawns(class APlayerController* PlayerController);
	void SpawnCharacterPawn(const struct FTransform& SpawnTransform, EPlayerClass Player_Class, class APlayerController* PC);
	void Team_Posible_Spawn(int32 Team, TArray<class ABP_PlayerSpawn_C*>& TeamSpawns, bool Bots, TArray<class ABP_PlayerSpawn_C*>* PosibleSpawn);
	void TimeDilationTimeline__FinishedFunc();
	void TimeDilationTimeline__UpdateFunc();
	void CheckGameOptions();
	void ManageNumberOfBots();
	void SVR_SetPointsToWin(int32 PointsToWin);
	void CreateBots();
	void SpawnBots();
	void SpawnPlayers();
	void SpawnCharacterWithClass(EPlayerClass PlayerClass, class APlayerController* PlayerController);
	void SpawnPlayerClass(EPlayerClass PlayerClass, class APlayerController* PlayerController);
	void Server_KickAllPlayers();
	void Server_RemovePC(class APlayerController* NewParam);
	void K2_OnLogout(class AController* ExitingController_K2_OnLogout);
	void Server_EndGame();
	void HandleStartingNewPlayer(class APlayerController* NewPlayer_HandleStartingNewPlayer);
	void ReceiveBeginPlay();
	void ResetGame(float Delay);
	void Server_ResetSpawns();
	void Server_GetKillFeedText(class APlayerState* Kill, class APlayerState* Vic, const class UDamageType* DmgType, class APlayerState* Assist, bool bHeadshot);
	void Server_UpdateScores();
	void InitializeHUDForPlayer(class APlayerController* NewPlayer);
	void Server_SendChatMessage(const class FText& TextToSend);
	void K2_PostLogin(class APlayerController* NewPlayer);
	void K2_OnSetMatchState(class FName NewState);
	void StartSlomo();
	void ExecuteUbergraph_BP_Base_GM(int32 EntryPoint);

	void GetGameWithBots(bool* bGameWithBots) const;
	void IsGameOver(bool* bGameOver) const;
	void IsFriendlyFireEnabled(bool* bEnabled) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Base_GM_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Base_GM_C")
	}
	static class ABP_Base_GM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Base_GM_C>();
	}
};
DUMPER7_ASSERTS_ABP_Base_GM_C;

SDK_NAMESPACE_END
