#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HealthComponent

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_HealthComponent.BP_HealthComponent_C
// 0x0008 (0x00B8 - 0x00B0)
class UBP_HealthComponent_C final : public UActorComponent
{
public:
	float                                         HP;                                                // 0x00B0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxHP;                                             // 0x00B4(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HealthComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HealthComponent_C")
	}
	static class UBP_HealthComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HealthComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_HealthComponent_C;

SDK_NAMESPACE_END
